name = "gg-cdn-pakrpp"
main = "src/worker.js"
compatibility_date = "2026-01-27"

[assets]
directory = "./public"
binding = "ASSETS"

[[routes]]
pattern = "www.pakrpp.com/assets/*"
zone_name = "pakrpp.com"

[[routes]]
pattern = "www.pakrpp.com/sw.js"
zone_name = "pakrpp.com"

[[routes]]
pattern = "www.pakrpp.com/manifest.webmanifest"
zone_name = "pakrpp.com"

[[routes]]
pattern = "www.pakrpp.com/offline.html"
zone_name = "pakrpp.com"

[[routes]]
pattern = "www.pakrpp.com/gg-pwa-icon/*"
zone_name = "pakrpp.com"
